### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by eminarican**

### CODE REVIEW

**Comment by fadeevab** [comment]
@eminarican  Hey! Thank you! Everything is fine, I just think "heapless" feature is not really needed here, isn't it?

**Comment by eminarican** [comment]
removed it ^^

**Review by fadeevab — DISMISSED** [review]
Looks good. Tested locally.

**Comment by fadeevab** [comment]
@eminarican Okay, just fix that formatting error:

```diff
Run cargo fmt -- --check
  cargo fmt -- --check
  shell: /usr/bin/bash -e {0}
Diff in /home/runner/work/cocoon/cocoon/src/mini.rs at line 1:
 use aes_gcm::{
     aead::{generic_array::GenericArray, NewAead},
-    AeadInPlace,
-    Aes256Gcm,
+    AeadInPlace, Aes256Gcm,
 };
```

**Review by fadeevab — APPROVED** [review]

**Comment by fadeevab** [comment]
Cocoon 0.2.4 has been published (https://crates.io/crates/cocoon).

**Pull request merged**
